import Navbar from "@/components/navbar/navbar";
import Sidebar from "@/components/sidebar/sidebar";
import { Toaster } from "@/components/ui/toaster";
import { menuProps, sidebarTitle } from "./menuProps";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="min-h-screen flex">
      <Sidebar title={sidebarTitle} menuProp={menuProps} />
      <div className="flex-1 p-6">
        <div className="p-4 bg-[#f9f9f9] flex justify-start items-end">
          asdsad
        </div>
        {children}
      </div>
      <Toaster />
    </div>
  );
}
